const PAGES = {
  home: { context: "General NomadsFi for Business enquiry", template: `
    <section class="hero"><div class="hero-copy"><p class="eyebrow">NomadsFi for Business</p><h1>Connectivity that <em>moves.</em></h1><p>NomadsFi brings global travel connectivity and portable connectivity expertise to teams, stores and operators that need to stay ready beyond the office.</p><div class="hero-actions"><button class="button js-open-contact" type="button">Talk to an Expert <span>-></span></button><a class="button button-quiet" href="/channel-partner">Explore the Partner Network</a></div></div><aside class="hero-data"><p>Global travel connectivity</p><strong>200+</strong><p>countries and territories referenced across NomadsFi travel connectivity</p></aside><div class="hero-orbit" aria-hidden="true"></div></section>
    <div class="ticker"><span>Global travel connectivity  -  Business continuity  -  International IoT  -  Partner Network  -  Carrier enablement  -  Global travel connectivity  -  Business continuity  -  International IoT</span></div>
    <section class="routes" id="routes"><div class="section-heading"><div><span class="section-kicker">01 / Find your route</span><h2>Built around how you move.</h2></div><p>Start where your connection need is sharpest. Every route leads to a focused conversation about product fit, rollout and support.</p></div><div class="route-list"><a class="route-card" href="/channel-partner"><span class="route-number">01</span><h3>Retail and local stores</h3><p>Wireless stores, retailers and convenience operators creating new portable-connectivity value at the counter.</p><span class="route-arrow">-></span></a><a class="route-card" href="/enterprise-connectivity"><span class="route-number">02</span><h3>Global employee travel</h3><p>An easier connectivity experience for teams on the move.</p><span class="route-arrow">-></span></a><a class="route-card" href="/enterprise-connectivity#failover"><span class="route-number">03</span><h3>Business failover</h3><p>Portable backup connectivity for locations that need an alternative path.</p><span class="route-arrow">-></span></a><a class="route-card" href="/carrier-iot#iot"><span class="route-number">04</span><h3>International IoT</h3><p>Multi-connection discussions for devices and fleets that cross borders.</p><span class="route-arrow">-></span></a><a class="route-card" href="/carrier-iot#carrier"><span class="route-number">05</span><h3>ISP and MVNO</h3><p>Coverage-led propositions for operators and their business customers.</p><span class="route-arrow">-></span></a></div></section>
    ${capabilities([['01','Travel connectivity without the handoff maze','Give travelling teams a practical route to staying connected across markets.'],['02','Portable continuity options','Explore a backup connectivity path for critical work and temporary locations.'],['03','One commercial conversation','Bring related global connectivity needs into a clearer partner discussion.'],['04','Support shaped around rollout','Start with the markets, use cases and people that will make the connection work.']])}
    ${caseSection('A distributed services team','Created a more consistent travel-connectivity approach for people moving between markets.',['Travel route review','Portable readiness','Partner support'])}
    ${processSection()} ${faqSection([{q:'What does NomadsFi for Business support?',a:'NomadsFi for Business starts with portable and global travel connectivity needs, with relevant discussions for business continuity, channel partners and operators.'},{q:'Where can travel connectivity be used?',a:'NomadsFi references connectivity across more than 200 countries and territories. Speak with an expert to confirm what fits your travel routes.'},{q:'Can you support a multi-country conversation?',a:'Yes. Start with the locations, user needs and rollout considerations that matter to your organisation.'}])} ${contactSection('Make mobility more connected.')}` },
  channel: { context: "NomadsFi Partner Network - Retail, wireless store or convenience store", template: `
    ${pageHero('For retailers, wireless stores and convenience operators','Make portable connectivity <em>sellable.</em>','NomadsFi Partner Network helps your team introduce portable and travel connectivity that customers can understand and take with them.')}
    <div class="audience-strip"><span>Designed for</span><strong>Retailer / Wireless Store / Convenience Store</strong></div>
    ${benefits([['Product value','Travel ready offers','Portable connectivity with a clear customer purpose: travel, temporary work and staying ready away from home.'],['Commercial model','Visible economics','A multi-tier commission and rebate structure built for transparency and scale. Specific commercial terms are discussed directly with NomadsFi.'],['Partner support','Ready teams','Product guidance and partner support designed around the way your team sells.']])}
    ${caseSection('An independent, multi-location retailer','Turned a high-intent travel question into a repeatable portable-connectivity category.',['Associate-ready playbook','Multi-tier earning path','Ongoing partner support'])}
    <section id="how-it-works"><div class="section-heading"><div><span class="section-kicker">02 / How partnership starts</span><h2>A route that respects your floor.</h2></div><p>We shape the product story, enable your people and stay close to the outcome.</p></div>${processSection(true)}</section>
    ${faqSection([{q:'How does the commission and rebate model work?',a:'NomadsFi uses a multi-tier commercial structure designed to be transparent and scalable. Terms, eligibility and rebate amounts are discussed directly for your business; no percentage assumptions are published.'},{q:'What types of stores can partner with NomadsFi?',a:'The Partner Network is intended for retailers, wireless stores and convenience operators where portable connectivity is relevant to customers.'},{q:'Will my team receive sales support?',a:'Partner enablement and product guidance are part of the launch conversation.'}])} ${contactSection('Build a stronger connectivity category.')}` },
  enterprise: { context: "NomadsFi for Business - Global travel or portable business failover", template: `
    ${pageHero('For enterprise travel and continuity leaders','One portable experience.<br><em>Wherever work goes.</em>','NomadsFi for Business supports global employee travel connectivity and portable business failover conversations for teams that work beyond a fixed location.')}
    <div class="audience-strip"><span>For</span><strong>IT / Operations / People and Travel / Procurement</strong></div>
    <section><div class="section-heading"><div><span class="section-kicker">01 / Connection for the work</span><h2>Travel ready. Continuity ready.</h2></div><p>Give employees a clearer way to connect when travelling, and explore a portable alternative for business locations that need a backup path.</p></div><div class="benefit-grid"><article class="benefit"><span class="section-kicker">Global travel</span><h3>200+ countries</h3><p>Review portable connectivity options for employees travelling across borders.</p></article><article class="benefit" id="failover"><span class="section-kicker">Business failover</span><h3>Stay ready</h3><p>Consider a portable backup option around important locations and temporary operations.</p></article><article class="benefit"><span class="section-kicker">Management</span><h3>One conversation</h3><p>Bring travel and portable continuity needs into a focused commercial discussion.</p></article></div></section>
    ${capabilities([['IT','Control without the sprawl','Start with the users, locations and device-management expectations you need to account for.'],['OPS','Protect the handoffs','Reduce uncertainty for mobile teams and important sites when the usual connection is unavailable.'],['PEOPLE','Look after travellers','Give employees a more practical connectivity option when they cross a border.'],['PROC','Make the choice accountable','Match coverage, commercial clarity and rollout support to the decision in front of you.']])}
    ${caseSection('A distributed professional services team','Created a more consistent portable connectivity plan for travellers and priority locations.',['Coverage review','Deployment discussion','One partner conversation'])}
    ${faqSection([{q:'Can NomadsFi support travel and business failover discussions?',a:'Yes. The first conversation can cover global employee travel connectivity and portable backup needs for locations that matter.'},{q:'How quickly can a deployment start?',a:'The appropriate path depends on the location, scale and solution. An expert can help map practical next steps.'},{q:'Which countries are covered?',a:'NomadsFi references connectivity across more than 200 countries and territories. Please confirm exact coverage for your routes with the team.'}])} ${contactSection('Give work a more dependable connection.')}` },
  carrier: { context: "NomadsFi for Business - International IoT, ISP or MVNO", template: `
    ${pageHero('For carrier, ISP, MVNO and IoT leaders','Make the connectivity opportunity <em>move.</em>','Three distinct buying routes for operators and connected-device businesses exploring international reach, portable continuity or a sharper customer proposition.')}
    <div class="audience-strip"><span>Built for</span><strong>International IoT / ISP portable continuity / MVNO propositions</strong></div>
    <section class="module-tabs"><div class="section-heading"><div><span class="section-kicker">01 / Choose the operating logic</span><h2>Same ambition. Different route.</h2></div><p>Select your focus to see the buying logic and conversation that fits it best.</p></div><div class="tabs" role="tablist" aria-label="NomadsFi carrier and IoT solutions"><button class="tab" role="tab" aria-selected="true" aria-controls="iot-panel" id="iot-tab" data-tab="iot">International IoT</button><button class="tab" role="tab" aria-selected="false" aria-controls="isp-panel" id="isp-tab" data-tab="isp">ISP and failover</button><button class="tab" role="tab" aria-selected="false" aria-controls="mvno-panel" id="mvno-tab" data-tab="mvno">MVNO</button></div><article class="module-panel active" role="tabpanel" id="iot-panel" aria-labelledby="iot-tab" data-panel="iot"><div><span class="section-kicker">International IoT / Multi-Connection</span><h3>Devices should not notice borders.</h3></div><div><p>Explore a multi-connection strategy for devices, assets and fleets that need to operate across markets.</p><ul><li>International footprint for connected deployments</li><li>Multi-connection discussion for device estates</li><li>Commercial and rollout conversation around scale</li></ul><button class="text-link js-open-contact" type="button" data-solution="International IoT / Multi-Connection">Discuss international IoT -&gt;</button></div></article><article class="module-panel" role="tabpanel" id="isp-panel" aria-labelledby="isp-tab" data-panel="isp"><div><span class="section-kicker">ISP / Pre-installed coverage and portable failover</span><h3>Make readiness part of the service.</h3></div><div><p>Explore a portable continuity proposition for business customers that need an alternative connection path.</p><ul><li>Portable backup aligned to your service model</li><li>Coverage and readiness discussion</li><li>Customer proposition and rollout support</li></ul><button class="text-link js-open-contact" type="button" data-solution="ISP portable coverage / Business failover">Discuss ISP failover -&gt;</button></div></article><article class="module-panel" role="tabpanel" id="mvno-panel" aria-labelledby="mvno-tab" data-panel="mvno"><div><span class="section-kicker">MVNO</span><h3>Build a more mobile proposition.</h3></div><div><p>Explore the connectivity and commercial ingredients that can help an MVNO create a more relevant offer for customers on the move.</p><ul><li>International connectivity proposition</li><li>Clear commercial route for operator discussions</li><li>Flexibility for audience-specific offers</li></ul><button class="text-link js-open-contact" type="button" data-solution="MVNO">Discuss an MVNO proposition -&gt;</button></div></article></section>
    ${caseSection('A growing connectivity operator','Mapped a mobile proposition around coverage, readiness and the commercial detail its customers needed.',['Defined buying route','Market-ready narrative','Launch support'])}
    ${faqSection([{q:'Which module is right for us?',a:'Use International IoT for connected devices and fleets, ISP and failover for portable continuity propositions, and MVNO for a customer-facing connectivity offer.'},{q:'Can one business discuss more than one route?',a:'Yes. Many operators have adjacent needs. The first conversation clarifies priorities before a commercial or technical plan is shaped.'},{q:'Do you support deployment discussions?',a:'NomadsFi can discuss deployment support appropriate to the solution, market and rollout scope.'}])} ${contactSection('Turn mobility into a sharper proposition.')}` }
};

function pageHero(kicker, title, text) { return `<section class="page-hero"><p class="eyebrow">${kicker}</p><h1>${title}</h1><p>${text}</p><button class="button js-open-contact" type="button">Talk to an Expert <span>-></span></button></section>`; }
function benefits(items) { return `<section><div class="section-heading"><div><span class="section-kicker">01 / A better route</span><h2>Simple to explain. Clear to own.</h2></div><p>Start with a customer need, then shape a NomadsFi offer that makes sense for your business.</p></div><div class="benefit-grid">${items.map(x=>`<article class="benefit"><span class="section-kicker">${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('')}</div></section>`; }
function capabilities(items) { return `<section class="capabilities"><div><span class="section-kicker">02 / What changes</span><h2>Less connection complexity. More readiness.</h2></div><div class="cap-list">${items.map(x=>`<article class="cap-item"><span>${x[0]}</span><div><h3>${x[1]}</h3><p>${x[2]}</p></div></article>`).join('')}</div></section>`; }
function caseSection(label, quote, stats) { return `<section class="case-grid"><div><span class="section-kicker">03 / A possible outcome</span><h2>From moving parts to forward motion.</h2><div class="case-stats">${stats.map((s,i)=>`<div><strong>0${i+1}</strong><span>${s}</span></div>`).join('')}</div></div><blockquote class="case-quote">"${quote}"<cite>Illustrative client scenario / details protected</cite></blockquote></section>`; }
function processSection(inner=false) { const content=`<div class="process-grid"><article class="process-item"><span>01</span><h3>Listen</h3><p>Start with the markets, teams, locations or customers that matter most.</p></article><article class="process-item"><span>02</span><h3>Shape</h3><p>Match the portable and global connectivity route to your operating reality.</p></article><article class="process-item"><span>03</span><h3>Launch</h3><p>Move through a practical rollout conversation with people who stay accountable.</p></article><article class="process-item"><span>04</span><h3>Grow</h3><p>Keep refining the connection as your organisation and opportunity move.</p></article></div>`; return inner ? content : `<section id="how-it-works"><div class="section-heading"><div><span class="section-kicker">04 / The NomadsFi way</span><h2>A partner for work in motion.</h2></div><p>We help make portable and travel connectivity work in the real world.</p></div>${content}</section>`; }
function faqSection(items) { return `<section class="faq"><div class="section-heading"><div><span class="section-kicker">Questions, answered</span><h2>Useful before we talk.</h2></div></div><div class="faq-list">${items.map(x=>`<details class="faq-item"><summary>${x.q}</summary><p>${x.a}</p></details>`).join('')}</div></section>`; }
function contactSection(title) { return `<section class="contact-cta" id="contact"><span class="section-kicker">A conversation can start here</span><h2>${title}</h2><p>Tell us what needs to connect, where it needs to work and what a better outcome looks like.</p><button class="button js-open-contact" type="button">Talk to an Expert <span>-></span></button></section>`; }

const path = window.location.pathname.replace(/\/$/, '') || '/';
const pageKey = path === '/channel-partner' ? 'channel' : path === '/enterprise-connectivity' ? 'enterprise' : path === '/carrier-iot' ? 'carrier' : 'home';
const page = PAGES[pageKey];
document.title = pageKey === 'home' ? 'NomadsFi for Business - Stay connected, wherever work goes' : `${pageKey === 'channel' ? 'NomadsFi Partner Network' : pageKey === 'enterprise' ? 'NomadsFi for Business' : 'NomadsFi Carrier and IoT'} - NomadsFi`;
document.querySelector('#main').innerHTML = page.template;
addPageVisuals(pageKey);
document.querySelector('#year').textContent = new Date().getFullYear();

function addPageVisuals(key) {
  const makeImage = (src, alt, hero = false) => {
    const image = document.createElement('img');
    image.src = src;
    image.alt = alt;
    image.width = 1536;
    image.height = 1024;
    image.decoding = 'async';
    if (hero) image.className = 'hero-image';
    else image.loading = 'lazy';
    return image;
  };
  if (key === 'home') {
    document.querySelector('.hero')?.prepend(makeImage('/assets/images/nomadsfi-global-travel-hero.png', 'Airport windows overlooking aircraft at blue hour, with an unbranded travel bag and portable connectivity device on a table', true));
    return;
  }
  const visual = document.createElement('section');
  visual.className = `supporting-visual${key === 'carrier' ? ' supporting-visual-dark' : ''}`;
  const asset = key === 'channel' ? '/assets/images/nomadsfi-partner-retail.png' : '/assets/images/nomadsfi-enterprise-iot.png';
  const alt = key === 'channel' ? 'Retail associate arranging an unbranded portable connectivity device and travel pouch at a modern store counter' : 'Anonymous traveller reviewing global connection routes beside unbranded portable connectivity devices';
  const title = key === 'channel' ? 'A partner offer your team can see.' : key === 'enterprise' ? 'A clearer view of work in motion.' : 'Map the opportunity across markets.';
  visual.innerHTML = `<div class="supporting-visual-copy"><span class="section-kicker">A closer look</span><h2>${title}</h2><p>Portable connectivity belongs in the moments where mobility, readiness and customer confidence meet.</p></div>`;
  visual.appendChild(makeImage(asset, alt));
  const anchor = key === 'carrier' ? document.querySelector('.module-tabs') : document.querySelector('.audience-strip');
  anchor?.insertAdjacentElement('afterend', visual);
}

const drawer = document.querySelector('#contact-drawer'); const region = document.querySelector('#bigin-form-region'); const context = document.querySelector('#contact-context'); let biginStarted=false; let lastFocused;
function openContact(event) { lastFocused=event?.currentTarget||document.activeElement; const solution=event?.currentTarget?.dataset.solution; context.textContent=solution ? `${page.context} - ${solution}` : page.context; drawer.classList.add('open'); drawer.setAttribute('aria-hidden','false'); document.body.style.overflow='hidden'; drawer.querySelector('.drawer-close').focus(); loadBigin(); }
function closeContact() { drawer.classList.remove('open'); drawer.setAttribute('aria-hidden','true'); document.body.style.overflow=''; lastFocused?.focus(); }
document.querySelectorAll('.js-open-contact').forEach(btn=>btn.addEventListener('click',openContact)); document.querySelectorAll('.js-close-contact').forEach(btn=>btn.addEventListener('click',closeContact)); document.addEventListener('keydown',event=>{if(event.key==='Escape'&&drawer.classList.contains('open'))closeContact();});
function loadBigin() { if(biginStarted)return; biginStarted=true; const script=document.createElement('script'); script.id='formScript7309635000000670253'; script.src='https://us.bigin.online/org917690855/forms/giftexpo?script=$sYG'; script.async=true; script.onload=()=>{region.setAttribute('aria-busy','false');const status=region.querySelector('.form-status');if(status)status.textContent='Secure contact form is ready below.';}; script.onerror=formFailure; document.body.appendChild(script); window.setTimeout(()=>{if(!region.querySelector('iframe, form, input, select, textarea')){const status=region.querySelector('.form-status');if(status&&status.textContent.includes('Loading'))formFailure();}},9000); }
function formFailure(){region.setAttribute('aria-busy','false');region.innerHTML='<p class="form-status error">The secure contact form could not load. Please try again later or use the contact method published by NomadsFi.</p>';}
document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{const target=tab.dataset.tab;document.querySelectorAll('.tab').forEach(x=>x.setAttribute('aria-selected',String(x===tab)));document.querySelectorAll('.module-panel').forEach(x=>x.classList.toggle('active',x.dataset.panel===target));history.replaceState(null,'',`#${target==='iot'?'iot':target==='isp'?'isp-failover':'carrier'}`);}));
if(pageKey==='carrier'&&location.hash){const key=location.hash==='#iot'?'iot':location.hash==='#isp'||location.hash==='#isp-failover'?'isp':location.hash==='#mvno'?'mvno':null;if(key)document.querySelector(`.tab[data-tab="${key}"]`)?.click();}
